/* Apply audit ratings to the app.  node audit/apply.js [--force]

   The auditor has final say on a problem's rating, because it is the only thing that actually reads the
   mathematics. This writes its ratings into content/audit-ratings.js, which the app loads and prefers
   over the contest-position seed.

   What the auditor does NOT override: your solve outcomes. Its rating is the starting value; the
   per-problem offset earned from real attempts still moves it. Freezing ratings against measured
   performance would defeat the point of the rating system.

   The calibration gate remains, but it is a malfunction check, not a request for approval: a run that
   cannot recover known contest ordering is broken, and applying it would corrupt every rating in the
   bank. --force overrides. */

const fs = require('fs');
const path = require('path');
const { load, calibrate } = require('./lib');

const force = process.argv.includes('--force');
const { rows, missing } = load();
const cal = calibrate(rows);

console.log(`Audit covers ${rows.length} problems (${cal.n} contest, ${rows.length - cal.n} authored).`);
if (cal.rho !== null) {
  console.log(`Calibration: rho=${cal.rho.toFixed(3)} MAE=${Math.round(cal.mae)} bias=${cal.bias >= 0 ? '+' : ''}${Math.round(cal.bias)} -> ${cal.verdict}`);
} else {
  console.log(`Calibration: ${cal.verdict} (too few contest problems to check)`);
}

if (missing.length) {
  console.log(`\nREFUSED: ${missing.length} problem(s) were not graded — the audit is incomplete.`);
  console.log(`Missing: ${missing.map(m => m.pid).join(', ')}`);
  console.log('Re-run the difficulty-auditor agent so every problem is covered.');
  if (!force) process.exit(1);
}

if ((cal.verdict === 'UNTRUSTWORTHY' || cal.verdict === 'UNKNOWN') && !force) {
  console.log(`\nREFUSED: verdict ${cal.verdict}.`);
  console.log('This means the blind audit could not recover the ordering of problems whose difficulty is');
  console.log('already known from contest position — which indicates the run malfunctioned, not that it');
  console.log('disagrees. Applying it would corrupt every rating. Re-run the audit, or use --force.');
  process.exit(1);
}
if (cal.verdict === 'WEAK') {
  console.log('\nWARNING: calibration is weak (rho between 0.4 and 0.7). Applying anyway, but the ratings');
  console.log('         carry more noise than usual; your solve outcomes will do more of the work.');
}

/* ---------- write ---------- */

const map = {};
for (const r of rows) map[r.pid] = r.rating;

const byPid = Object.fromEntries(rows.map(r => [r.pid, r]));
const lines = Object.keys(map).sort().map(pid => {
  const r = byPid[pid];
  const note = r.authored ? 'authored' : `was ${r.seedRating}`;
  return `  '${pid}': ${map[pid]},`.padEnd(34) + `// ${r.band} ${r.confidence}, ${note}`;
});

const out = `/* GENERATED by audit/apply.js — do not edit by hand.
   Difficulty ratings from the blind content audit. The app prefers these over contest-position seeds:
   contest position is a coarse proxy, and problems vary a lot within one position.

   These are starting values, not frozen truth — the per-problem offset earned from your real solve
   outcomes still moves them. Regenerate with:
     node audit/extract.js  ->  difficulty-auditor agent  ->  node audit/apply.js

   Calibration of the run that produced this file:
     Spearman rho ${cal.rho === null ? 'n/a' : cal.rho.toFixed(3)} vs contest-position seeds (n=${cal.n}), MAE ${cal.mae === null ? 'n/a' : Math.round(cal.mae)}, verdict ${cal.verdict}.
   Generated ${new Date().toISOString().slice(0, 10)}. */

PT.registerAuditRatings({
${lines.join('\n')}
});
`;

const target = path.join(__dirname, '..', 'content', 'audit-ratings.js');
fs.writeFileSync(target, out);

console.log(`\nWrote ${Object.keys(map).length} ratings to content/audit-ratings.js`);

const moved = rows
  .filter(r => !r.authored && Math.abs(r.delta) >= 200)
  .sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta));
if (moved.length) {
  console.log('\nLargest changes to contest problems:');
  for (const r of moved) {
    console.log(`  ${r.pid.padEnd(12)} ${r.seedRating} -> ${r.rating}  (${r.delta > 0 ? '+' : ''}${r.delta})`);
  }
}

const auth = rows.filter(r => r.authored);
if (auth.length) {
  const lo = Math.min(...auth.map(r => r.rating)), hi = Math.max(...auth.map(r => r.rating));
  console.log(`\nAuthored problems now span ${lo}-${hi} instead of all sitting at the drill floor.`);
}

console.log('\nMake sure index.html loads content/audit-ratings.js, then run: node test.js');
